# -*- coding: utf-8 -*-
"""TomásCatalán_PGY1121_006_V.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wkBCA5yaOKwaxzuhI_mUK_H93A-3lRLa
"""

import random
lotes = []

n = 5
m = 4

"""
info_lote = {
    "comprado" : False,
    "numero_lote" : 0,
    "tamaÃ±o" : 0,
    "precio" : 0,
    "cliente" : None
}

info_cliente = {
    "nombre" : "",
    "rut" : "",
    "telefono" : "",
    "email" : ""
}
"""




info_lote_2 = [False, 0,0,0,["","",0,""]]
x_ultimo_lote_comprado = 0
y_ultimo_lote_comprado = 0
seq_id_lote = 1


for i in range(m):
    temp_lista = []
    for i in range(n):
        terreno = random.randint(10, 100)
        precio = random.randint(5000, 10000)
        temp_info_lote = [False, str(terreno) +' M2', str(precio) +' UF', 0,["","",0,""]]
        temp_lista.append(temp_info_lote)
    lotes.append(temp_lista)



def imprimir_lotes():
    for i in lotes:
        for lote in i:
            if(lote[0] == True):
                print("[X]",end=" ")
            else:
                print("[]",end=" ")
        print("\n")
def imprimir_clientes():
    cantidad_clientes = 0
    for i in lotes:
        for lote in i:
            if(lote[0] == True):
                cantidad_clientes += 1
                print(lote[4])
    print(f"Hay {cantidad_clientes} clientes almacenados")
def Escojer_Lote():
    #El global es para que la variable tenga asignado un valor
    global x_ultimo_lote_comprado
    global y_ultimo_lote_comprado
    global seq_id_lote
    while True:

        fila = int(input("Ingrese Fila: "))
        col = int(input("Ingrese Columna: "))

        if(fila > m or fila < 0 or col > n or col < 0):
            print("Coordenada fuera de rango")
            continue
        if(lotes[fila][col][0] == True):
            print("Lote ya ocupado")
            continue


        lotes[fila][col][4][0] = input("Nombre: ")
        lotes[fila][col][4][1] = input("Rut: ")
        lotes[fila][col][4][2] = input("Telefono: ")
        lotes[fila][col][4][3] = input("Email: ")

        lotes[fila][col][0] = True
        lotes[fila][col][3] = str(seq_id_lote) +'. ID Terreno'
        seq_id_lote += 1

        #Este asignacion no esta funcionando, el opcion 3 va a mostrar todos los lotes
        x_ultimo_lote_comprado = fila
        y_ultimo_lote_comprado = col


        break


def menu():
    while True:
        opcion = int(input("Seleccione una opción \n 1.Disponibilidad de Lotes \n 2.Escoger Lote \n 3.Información de lote escogido \n 4.Imprimir Clientes \n 5.Salir \n"))

        if(opcion == 1):
            imprimir_lotes()
        elif(opcion == 2):
            Escojer_Lote()
        elif(opcion == 3):
            print(lotes[x_ultimo_lote_comprado][y_ultimo_lote_comprado][1:4])
            print(lotes[x_ultimo_lote_comprado][y_ultimo_lote_comprado][4])
        elif(opcion == 4):
            imprimir_clientes()
        elif(opcion == 5):
            break
        else:
            print("opcion no valida")
menu()